import type { Processo } from "./types";

const agora = new Date().toISOString();

export function processoDemonstrativo(): Processo {
  return {
    id: "demo-2026-114",
    numero: "114/2026",
    tribunal: "Tribunal Judicial da Cidade de Maputo",
    seccao: "2.ª Secção Criminal",
    juiz: "Dr.(a) Juiz de Direito",
    arguidos: "A. M. C., solteiro, 29 anos, residente no Bairro Polana Caniço A",
    ofendidos: "L. S. N., residente no Bairro Sommerschield",
    crimes: "Furto qualificado; Ofensa corporal simples",
    data: "2026-05-14",
    estado: "analise",
    criadoEm: agora,
    actualizadoEm: agora,
    documentos: [
      {
        id: "doc-acusacao",
        nome: "Acusacao_MP_114-2026.pdf",
        tipo: "acusacao",
        tamanho: 184320,
        mime: "application/pdf",
        paginas: 6,
        estadoOcr: "processado",
        textoExtraido:
          "MINISTÉRIO PÚBLICO — ACUSAÇÃO\n\nO Ministério Público acusa A. M. C. de, no dia 3 de Março de 2026, cerca das 21h30, no Bairro Sommerschield, se ter introduzido na residência do ofendido L. S. N., de onde retirou um computador portátil e um telemóvel, no valor global estimado de 85.000,00 MT, tendo ainda desferido um empurrão no ofendido, causando-lhe escoriações no antebraço direito.\n\nRol de testemunhas: L. S. N. (ofendido); J. P. (vizinho); Agente da PRM de serviço.\nProva documental: auto de notícia; auto de apreensão; relatório de exame médico-legal; factura do computador.",
        criadoEm: agora,
      },
      {
        id: "doc-acta",
        nome: "Acta_Audiencia_09-05-2026.pdf",
        tipo: "acta",
        tamanho: 246800,
        mime: "application/pdf",
        paginas: 11,
        estadoOcr: "processado",
        textoExtraido:
          "ACTA DA AUDIÊNCIA DE JULGAMENTO — 09 de Maio de 2026\n\nO arguido, ouvido, confessou parcialmente os factos: admitiu ter retirado o telemóvel, negando a subtracção do computador e negando qualquer agressão.\n\nDeclarações do ofendido L. S. N.: confirmou o desaparecimento do computador e do telemóvel; declarou não ter visto o momento da subtracção do computador; confirmou o empurrão.\n\nTestemunha J. P.: declarou ter visto o arguido a sair do quintal com um objecto na mão, sem conseguir precisar qual.\n\nTestemunha Agente da PRM: descreveu a detenção e a apreensão do telemóvel na posse do arguido, cerca de duas horas depois.\n\nO arguido esteve detido de 3 a 17 de Março de 2026.",
        criadoEm: agora,
      },
      {
        id: "doc-provas",
        nome: "Provas_documentais.pdf",
        tipo: "prova",
        tamanho: 512000,
        mime: "application/pdf",
        paginas: 14,
        estadoOcr: "processado",
        textoExtraido:
          "Auto de apreensão: telemóvel marca X, IMEI ...4471, apreendido ao arguido.\nFactura do telemóvel em nome do ofendido, IMEI coincidente.\nRelatório de exame médico-legal: escoriações superficiais no antebraço direito, compatíveis com traumatismo, 3 dias de doença sem incapacidade para o trabalho.\nNão consta dos autos qualquer documento relativo ao computador portátil.",
        criadoEm: agora,
      },
    ],
    provas: [
      {
        id: "pv-1",
        referencia: "Auto de apreensão (fls. 12)",
        tipo: "documental",
        descricao: "Telemóvel apreendido na posse do arguido, IMEI ...4471.",
        origemDocumentoId: "doc-provas",
        utilizavel: true,
      },
      {
        id: "pv-2",
        referencia: "Factura do telemóvel (fls. 15)",
        tipo: "documental",
        descricao: "Factura em nome do ofendido, IMEI coincidente com o apreendido.",
        origemDocumentoId: "doc-provas",
        utilizavel: true,
      },
      {
        id: "pv-3",
        referencia: "Exame médico-legal (fls. 18)",
        tipo: "pericial",
        descricao: "Escoriações no antebraço direito; 3 dias de doença sem incapacidade.",
        origemDocumentoId: "doc-provas",
        utilizavel: true,
      },
      {
        id: "pv-4",
        referencia: "Declarações do arguido (acta, 09-05-2026)",
        tipo: "declaracoes",
        descricao: "Confissão parcial: admite o telemóvel, nega o computador e a agressão.",
        origemDocumentoId: "doc-acta",
        utilizavel: true,
      },
      {
        id: "pv-5",
        referencia: "Declarações do ofendido (acta, 09-05-2026)",
        tipo: "testemunhal",
        descricao: "Não presenciou a subtracção do computador; confirma o empurrão.",
        origemDocumentoId: "doc-acta",
        utilizavel: true,
      },
      {
        id: "pv-6",
        referencia: "Testemunho de J. P. (acta, 09-05-2026)",
        tipo: "testemunhal",
        descricao: "Viu o arguido a sair com objecto não identificado.",
        origemDocumentoId: "doc-acta",
        utilizavel: true,
        observacao: "Valor probatório limitado quanto à identificação do objecto.",
      },
    ],
    factos: [
      {
        id: "ft-1",
        numero: 1,
        texto:
          "No dia 3 de Março de 2026, cerca das 21h30, o arguido introduziu-se na residência do ofendido, no Bairro Sommerschield.",
        categoria: "provado",
        natureza: "prova",
        confianca: 82,
        provasIds: ["pv-4", "pv-5", "pv-6"],
        origem: "Acta da audiência (declarações do arguido e do ofendido)",
        estado: "pendente",
        alertas: [],
      },
      {
        id: "ft-2",
        numero: 2,
        texto: "O arguido retirou da residência um telemóvel pertencente ao ofendido.",
        categoria: "provado",
        natureza: "prova",
        confianca: 94,
        provasIds: ["pv-1", "pv-2", "pv-4"],
        origem: "Auto de apreensão, factura e confissão parcial",
        estado: "pendente",
        alertas: [],
      },
      {
        id: "ft-3",
        numero: 3,
        texto:
          "Em consequência de um empurrão desferido pelo arguido, o ofendido sofreu escoriações no antebraço direito, com 3 dias de doença sem incapacidade para o trabalho.",
        categoria: "provado",
        natureza: "prova",
        confianca: 71,
        provasIds: ["pv-3", "pv-5"],
        origem: "Exame médico-legal e declarações do ofendido",
        estado: "pendente",
        alertas: [
          "O arguido nega a agressão — apreciação crítica deve confrontar a versão do ofendido com o exame médico-legal.",
        ],
      },
      {
        id: "ft-4",
        numero: 4,
        texto:
          "O arguido agiu de forma livre, voluntária e consciente, sabendo que a sua conduta era proibida e punida por lei.",
        categoria: "provado",
        natureza: "inferencia",
        confianca: 63,
        provasIds: ["pv-4"],
        origem: "Inferência a partir do conjunto da prova",
        estado: "pendente",
        alertas: [
          "Facto de natureza inferencial (elemento subjectivo): exige fundamentação autónoma e não pode resultar da mera transcrição da acusação.",
        ],
      },
      {
        id: "ft-5",
        numero: 5,
        texto: "O arguido retirou da residência um computador portátil pertencente ao ofendido.",
        categoria: "nao_provado",
        natureza: "alegacao",
        confianca: 22,
        provasIds: [],
        origem: "Acusação (não corroborada por prova produzida em audiência)",
        estado: "pendente",
        alertas: [
          "Alegação da acusação sem suporte probatório: nem o ofendido nem a testemunha presenciaram a subtracção; nenhum documento nos autos. In dubio pro reo.",
        ],
      },
    ],
    elementos: [
      {
        id: "el-1",
        crime: "Furto",
        baseLegal: "Código Penal (Lei n.º 24/2019) — artigo a confirmar",
        baseLegalConfirmada: false,
        elemento: "Subtracção de coisa móvel alheia",
        tipoElemento: "objectivo",
        provasIds: ["pv-1", "pv-2", "pv-4"],
        preenchido: "sim",
      },
      {
        id: "el-2",
        crime: "Furto",
        baseLegal: "Código Penal (Lei n.º 24/2019) — artigo a confirmar",
        baseLegalConfirmada: false,
        elemento: "Intenção de apropriação (dolo específico)",
        tipoElemento: "subjectivo",
        provasIds: ["pv-4"],
        preenchido: "sim",
        nota: "Inferido da detenção do bem duas horas depois dos factos.",
      },
      {
        id: "el-3",
        crime: "Furto qualificado",
        baseLegal: "Código Penal (Lei n.º 24/2019) — circunstância qualificativa a confirmar",
        baseLegalConfirmada: false,
        elemento: "Circunstância qualificativa (introdução em residência)",
        tipoElemento: "objectivo",
        provasIds: ["pv-5", "pv-6"],
        preenchido: "duvidoso",
        nota: "CONFIRMAR BASE LEGAL da qualificativa e o respectivo enquadramento antes de citar.",
      },
      {
        id: "el-4",
        crime: "Ofensa corporal simples",
        baseLegal: "Código Penal (Lei n.º 24/2019) — artigo a confirmar",
        baseLegalConfirmada: false,
        elemento: "Ofensa ao corpo ou à saúde de outrem",
        tipoElemento: "objectivo",
        provasIds: ["pv-3"],
        preenchido: "sim",
      },
      {
        id: "el-5",
        crime: "Ofensa corporal simples",
        baseLegal: "Código Penal (Lei n.º 24/2019) — artigo a confirmar",
        baseLegalConfirmada: false,
        elemento: "Dolo (conhecimento e vontade de ofender)",
        tipoElemento: "subjectivo",
        provasIds: ["pv-5"],
        preenchido: "duvidoso",
        nota: "Arguido nega; ponderar in dubio pro reo caso a prova não seja suficiente.",
      },
    ],
    fundamentos: [
      {
        id: "fd-1",
        seccao: "questoes",
        titulo: "Questões a resolver",
        texto:
          "1. Apurar se o arguido subtraiu os bens descritos na acusação.\n2. Determinar se se verifica a circunstância qualificativa imputada.\n3. Apurar a existência da ofensa corporal.\n4. Em caso afirmativo, determinar a qualificação jurídica, a medida concreta da pena e o eventual concurso.\n5. Apreciar a responsabilidade civil emergente do crime, se pedida.",
        baseLegalConfirmada: true,
        estado: "pendente",
        alertas: [],
      },
      {
        id: "fd-2",
        seccao: "facto",
        titulo: "Apreciação crítica da prova",
        texto:
          "A convicção do Tribunal formou-se na análise conjugada e crítica da prova produzida em audiência. Quanto ao telemóvel, a confissão parcial do arguido é corroborada pelo auto de apreensão e pela factura com IMEI coincidente, o que confere solidez ao facto n.º 2. Quanto ao computador, a acusação não foi corroborada: o ofendido não presenciou a subtracção e a testemunha J. P. não identificou o objecto, pelo que, por aplicação do princípio in dubio pro reo, o facto foi dado como não provado. Quanto à ofensa corporal, o exame médico-legal documenta lesões compatíveis com a versão do ofendido, versão que o Tribunal considerou credível pela sua espontaneidade e coerência, não sendo a negação do arguido suficiente para infirmar a prova pericial.",
        baseLegalConfirmada: true,
        estado: "pendente",
        alertas: [],
      },
      {
        id: "fd-3",
        seccao: "qualificacao",
        titulo: "Qualificação jurídica",
        texto:
          "Os factos provados integram, em tese, a prática de um crime de furto e de um crime de ofensa corporal simples, previstos e punidos pelo Código Penal (Lei n.º 24/2019, com a alteração da Lei n.º 17/2020). A qualificativa imputada não resulta suficientemente demonstrada.",
        baseLegal: "Lei n.º 24/2019 — artigos a confirmar",
        baseLegalConfirmada: false,
        estado: "pendente",
        alertas: ["CONFIRMAR BASE LEGAL: artigos não validados na Biblioteca Jurídica."],
      },
      {
        id: "fd-4",
        seccao: "circunstancias",
        titulo: "Circunstâncias agravantes e atenuantes",
        texto:
          "Atenuantes: confissão parcial; ausência de antecedentes criminais conhecidos; juventude do arguido; reduzido valor do bem efectivamente subtraído.\nAgravantes: a ponderar, com indicação expressa da base legal.",
        baseLegal: "Código Penal (Lei n.º 24/2019) — artigos a confirmar",
        baseLegalConfirmada: false,
        estado: "pendente",
        alertas: [
          "Dupla valoração: a circunstância que integra o tipo de crime não pode ser novamente valorada como agravante.",
        ],
      },
      {
        id: "fd-5",
        seccao: "pena",
        titulo: "Medida concreta da pena",
        texto:
          "A pena será fixada em função da culpa do agente e das exigências de prevenção geral e especial, ponderando o grau de ilicitude, o modo de execução, a intensidade do dolo, as condições pessoais e a conduta anterior e posterior aos factos.",
        baseLegal: "Código Penal (Lei n.º 24/2019) — artigos a confirmar",
        baseLegalConfirmada: false,
        estado: "pendente",
        alertas: ["CONFIRMAR BASE LEGAL dos critérios de determinação da medida da pena."],
      },
      {
        id: "fd-6",
        seccao: "desconto",
        titulo: "Desconto da detenção",
        texto:
          "O arguido esteve detido de 3 a 17 de Março de 2026 (14 dias), período que deverá ser descontado na pena a aplicar, nos termos legais.",
        baseLegal: "Código Penal (Lei n.º 24/2019) — artigo a confirmar",
        baseLegalConfirmada: false,
        estado: "pendente",
        alertas: [],
      },
      {
        id: "fd-7",
        seccao: "civil",
        titulo: "Responsabilidade civil emergente do crime",
        texto:
          "Não consta dos autos pedido de indemnização civil devidamente deduzido e quantificado. A existir, deverá ser apreciado apenas na medida do dano provado.",
        baseLegalConfirmada: true,
        estado: "pendente",
        alertas: [],
      },
      {
        id: "fd-8",
        seccao: "custas",
        titulo: "Custas",
        texto: "Custas pelo arguido, nos termos legais, na medida do decaimento.",
        baseLegal: "CPP (Lei n.º 25/2019) — artigo a confirmar",
        baseLegalConfirmada: false,
        estado: "pendente",
        alertas: [],
      },
      {
        id: "fd-9",
        seccao: "apreendidos",
        titulo: "Destino dos bens apreendidos",
        texto: "Restituição do telemóvel apreendido ao ofendido, após trânsito em julgado.",
        baseLegal: "CPP (Lei n.º 25/2019) — artigo a confirmar",
        baseLegalConfirmada: false,
        estado: "pendente",
        alertas: [],
      },
    ],
    contradicoes: [
      {
        id: "ct-1",
        descricao:
          "A acusação afirma a subtracção do computador; a acta revela que nem o ofendido nem a testemunha presenciaram tal subtracção e não existe documento que a suporte.",
        fontes: ["Acusacao_MP_114-2026.pdf", "Acta_Audiencia_09-05-2026.pdf"],
        gravidade: "alta",
      },
      {
        id: "ct-2",
        descricao:
          "A acusação descreve um empurrão com escoriações; o arguido nega integralmente a agressão em audiência.",
        fontes: ["Acusacao_MP_114-2026.pdf", "Acta_Audiencia_09-05-2026.pdf"],
        gravidade: "media",
      },
    ],
    lacunas: [
      "Ausência de prova documental ou testemunhal quanto ao computador portátil.",
      "Não consta certificado de registo criminal actualizado do arguido.",
      "Não consta pedido de indemnização civil formalmente deduzido.",
      "Base legal dos artigos citados por validar na Biblioteca Jurídica.",
    ],
    minuta: {},
    versoes: [],
    comentarios: [],
    auditoria: [
      { id: "au-1", accao: "Processo demonstrativo criado", quando: agora, autor: "Sistema" },
    ],
  };
}
